### PR TITLE
Refactoring and image output

### LINKED ISSUE #7: Refactor FIIconView into FIIconLayer
Struggling with simply setting icons to buttons I wondered whether it'd be more accessible implementing rasterization subclassing CALayer that could be composed into any UIView?

### PR DESCRIPTION
**Pull request by texastoland**
- Version and reformat podspec
- Ignore AppCode files
- Refactor drawing into `CALayer` subclass closes #7
- Fix miscalculations and support fixed aspect ratio by default
- ~~Draw using `UIKit` instead of `CoreGraphics`~~
- Selectors rendering `UIImage`
- Icon view and layer share a protocol
- Icon view just forwards missing methods to its layer
- Padding proxies to inset to accommodate different axes
- Icon selector to retrieve by font name
- Integrate new features into sample app
- Adhere closely to style conventions

### CODE REVIEW

**Comment by texastoland** [comment]
Closing this for now because it broke in my project by switching to `UIKit`'s rendering. But `UIKit` can't use `CTFont`s loaded at runtime without private API called `GSFontAddFromFile` or listing them in your plist's `Fonts provided by application`. Even though on OS X they're toll-free bridged :japanese_goblin: I'll probably switch back to `CoreText` this weekend after trying again. Could you merge what I have into a patch or dev branch for review in the meantime? I'm also available to explain my reasoning. I know it looks like a lot [changed](https://github.com/AlexDenisov/FontasticIcons/pull/8/files) but 80% was breaking down `FIIconView` into composable pieces grouped as `FIIconRendering`. The abstraction enables anyone to come along and do crazy stuff like layer effects over their icon. And `FIIconLayer` itself can be composed into any other `UIView` without subclassing.

**Comment by texastoland** [comment]
Fixed with pictures :japanese_ogre:

| After | Before |
| --- | --- |
| After | Before |

**Comment by AlexDenisov** [comment]
That's awesome :+1:

**Comment by AlexDenisov** [comment]
Crashes on iOS 5.x. =(((

**Comment by texastoland** [comment]
Apparently `UIColor` [didn't conform](https://github.com/nst/iOS-Runtime-Headers/blob/5.1/Frameworks/UIKit.framework/UIColor.h) to `NSCopying` till [6.0](https://github.com/nst/iOS-Runtime-Headers/blob/master/Frameworks/UIKit.framework/UIColor.h). I'll switch to `retain`. Testing back to 4.3 now. Separate pull request and replace the tag?

**Comment by AlexDenisov** [comment]
<blockquote>Separate pull request and replace the tag?</blockquote>

It would be nice :smile:

**Pull request merged**
