### PR TITLE
Fix retina rendering regression

### PR DESCRIPTION
**Pull request by texastoland**
Would it be okay to squeeze this into 0.2.0? Otherwise it would break API. Replying about subpixel aliasing now for 0.2.1.

### CODE REVIEW

**Comment by AlexDenisov** [comment]
@dnalot, thank you so much!

**Comment by texastoland** [comment]
Whoops I just noticed one minor bug where I referenced [`UIScreen#scale`](https://github.com/dnalot/FontasticIcons/blob/eab9ef1c53331fe06cb44925c6b15223d7434b45/FontasticIcons/Sources/Classes/FIIconLayer.m#L52) outside my version check. Would you prefer to cherry pick it or another PR?

**Comment by AlexDenisov** [comment]
Another PR would be great

**Comment by texastoland** [comment]
I fixed it but don't know how to test compliance for 3.2 (when `CoreText` became available)? Is that support desired? Otherwise I could pull my fences around `dispatcth_once()` and DIP scaling and raise the requirement in the `podspec`.

**Comment by AlexDenisov** [comment]
I think that 4.3 is enough.

**Pull request merged**
